{% set name = "qpmpc" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qpmpc-{{ version }}.tar.gz
  sha256: 5394acc4969159c03af946a522b62d510617da090cb755805dc248b4e0ebe567

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - qpsolvers >=1.8.0

test:
  imports:
    - qpmpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/qpmpc
  summary: Linear time-variant model predictive control in Python.
  dev_url: https://github.com/stephane-caron/qpmpc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
